//tipo de acciones
export const SET_LOADING_LOGIN = "SET_LOADING_LOGIN";

export const LOGIN_USER_WITH_EMAIL_PASSWORD = "LOGIN_USER_WITH_EMAIL_PASSWORD";

export const LOGIN_USER_WITH_EMAIL_PASSWORD_SUCCESS =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_SUCCESS";

export const LOGIN_USER_WITH_EMAIL_PASSWORD_ERROR =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_ERROR";
