//tipo de acciones
export const LOGIN_USER_WITH_EMAIL_PASSWORD_PENDING =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_PENDING";

export const LOGIN_USER_WITH_EMAIL_PASSWORD = "LOGIN_USER_WITH_EMAIL_PASSWORD";

export const LOGIN_USER_WITH_EMAIL_PASSWORD_SUCCESS =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_SUCCESS";

export const LOGIN_USER_WITH_EMAIL_PASSWORD_ERROR =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_ERROR";
