//tipo de acciones
export const LOG_OUT = "LOG_OUT";

export const LOGIN_USER_WITH_EMAIL_PASSWORD_PENDING =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_PENDING";

export const LOGIN_USER_WITH_EMAIL_PASSWORD = "LOGIN_USER_WITH_EMAIL_PASSWORD";

export const LOGIN_USER_WITH_EMAIL_PASSWORD_SUCCESS =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_SUCCESS";

export const LOGIN_USER_WITH_EMAIL_PASSWORD_ERROR =
  "LOGIN_USER_WITH_EMAIL_PASSWORD_ERROR";

export const ADD_CARD = "ADD_CARD";

export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";

export const DELETE_CARD = "DELETE_CARD";
